# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e035a2df67ae16a3399334d69618338acf81b928bf05f005752d8940ff253e838de90ab6e6602d1b994d39c87b44bb98f562b97bb34df67e2b74efc9b261d26
  soda_API: m1qB29JXSOdh6RW6xpSUsF6Oy
  google_API: AIzaSyCN0EFji6YhrnAOjacp2bR_BBwM0Z30glI # this API had to be included in the "show.html.erb"

test:
  secret_key_base: 7999173925cbe4af770572dda6dea246d5d353767b7857c53ce7948f20e92734f320fb0c7486698d4821a4dd8541e9cb0283a40a976388c2495344f0b6de34eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  soda_API: <%= ENV["soda_API"] %>
  google_API: <%= ENV["google_API"] %>
